// Generated by CoffeeScript 1.4.0
(function() {
  var app;

  app = angular.module('app');

  app.controller('IndexCtrl', [
    '$scope', function($scope) {
      return $scope.title = 'My Angular.js Application';
    }
  ]);

}).call(this);
