// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('app', []).config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/', {
        templateUrl: 'views/index.html',
        controller: 'IndexCtrl'
      });
      return $routeProvider.otherwise({
        redirectTo: '/'
      });
    }
  ]).config([
    '$locationProvider', function($locationProvider) {
      $locationProvider.html5Mode(true);
      return $locationProvider.hashPrefix('!');
    }
  ]);

}).call(this);
