// Generated by CoffeeScript 1.3.3
(function() {
  var controllers, homeController;

  controllers = ['movie'];

  homeController = function(app) {
    return app.get('/', function(req, res) {
      return res.render('index', {
        title: 'MovieDB'
      });
    });
  };

  exports.init = function(app) {
    var c, controller, _i, _len, _results;
    homeController(app);
    _results = [];
    for (_i = 0, _len = controllers.length; _i < _len; _i++) {
      controller = controllers[_i];
      c = require("./" + controller);
      c(app);
      _results.push(console.log(c));
    }
    return _results;
  };

}).call(this);
