// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  describe("Test 1", function() {
    return it("should pass", function() {
      var i;
      i = 9;
      return expect(i).toEqual(9);
    });
  });

  describe('test 2', function() {
    return it('should fail', function() {
      var pi;
      pi = 2.8;
      return expect(pi).toEqual(9);
    });
  });

}).call(this);
